[package]
name = "boringtun" # todo
description = "an implementation of the WireGuard® protocol designed for portability and speed"
version = "0.6.0"
authors = [
    "Noah Kennedy <nkennedy@cloudflare.com>",
    "Andy Grover <agrover@cloudflare.com>",
    "Jeff Hiner <jhiner@cloudflare.com>",
    "Mullvad VPN",
]
license = "BSD-3-Clause"
repository = "https://github.com/mullvad/gotatun"
edition = "2024"

[features]
default = []
device = ["thiserror"]
pcap = ["dep:pcap-file"]
# UDP GRO appears to be broken on Windows.
# In some cases it fails to return UDP_COALESCED_INFO
windows-gro = []

[dependencies]
base64 = "0.13"
hex = "0.4"
untrusted = "0.9.0"
libc = "0.2"
parking_lot = "0.12"
tracing = "0.1.40"
ip_network = "0.4.1"
ip_network_table = "0.2.0"
ring = "0.17"
x25519-dalek = { version = "2.0.0", features = [
    "reusable_secrets",
    "static_secrets",
] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
chacha20poly1305 = "0.10.0-pre.1"
aead = "0.5.0-pre.2"
blake2 = "0.10"
hmac = "0.12"
mock_instant = { version = "0.3", optional = true }
socket2 = { version = "0.6.0", features = ["all"] }
thiserror = { version = "1", optional = true }
tokio = { version = "1.43.0", features = ["full"] }
eyre = "0.6.12"
log = "0.4"
typed-builder = "0.21.0"
tun = { version = "0.7.13", features = ["async"], optional = true }
async-trait = "0.1.88"
zerocopy = { version = "0.8.26", features = ["std", "derive"] }
pnet_packet = "0.35.0"
bytes = "1.10.1"
either = "1.15.0"
bitfield-struct = "0.11.0"
rand = "0.9.2"

pcap-file = { version = "2.0.0", optional = true }
duplicate = { version = "2.0.0", default-features = false }
constant_time_eq = "0.4.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61.0", features = [
    "Win32",
    "Win32_Foundation",
    "Win32_Networking",
    "Win32_Networking_WinSock",
    "Win32_System_IO",
] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.30", default-features = false, features = [
    "time",
    "user",
    "socket",
    "uio",
    "net",
] }

[dev-dependencies]
etherparse = "0.13"
tracing-subscriber = "0.3"
criterion = { version = "0.7.0", features = ["html_reports"] }

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[[bench]]
name = "crypto_benches"
harness = false

[[bench]]
name = "throughput_benches"
harness = false
